### ISSUE TITLE
Skip not working on first project

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/tartanhacks-judging#35]
Skip feature not working on first project

**Comment by pm3512** [comment]
Some details: when logged in as a judge, if the user has not judged any projects and they attempt to skip the first project (Get next project -> skip), the project will not be skipped. To see hints on how to approach the problem, see https://www.notion.so/scottylabs-cmu/Bootcamp-TH-Registration-and-Judging-825b4e8a30c7448a83d0bf823dd1d402?pvs=4#b0d2d2848a1048e7bbbfc8d3bb4a4f1e
