### ISSUE TITLE
[Feature] Make message saying "Time's Up!"

### ISSUE THREAD

**Issue by gramliu** [ScottyLabs/tartanhacks-judging#41]
### Description

When judging deadline elapses, make message that says "Time's Up!" instead of displaying a negative counter

**Comment by pm3512** [comment]
Additionally, once the deadline elapses, the interval updating the timer should no longer tick. For more details and hints, see https://www.notion.so/scottylabs-cmu/Bootcamp-TH-Registration-and-Judging-825b4e8a30c7448a83d0bf823dd1d402?pvs=4#e537412e6c754acba2e3f5dbe99dcd87
